# Generated by Django 3.2.4 on 2021-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rate', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='sample/')),
            ],
        ),
    ]
