# Generated by Django 3.2.4 on 2021-10-10 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobnumber', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=25)),
                ('state', models.CharField(default='', max_length=15)),
                ('zip', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=60)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ON PROCESS', 'ON Process'), ('DELIEVERED', 'Delieverd'), ('ORDER PLACED', 'Order Placed'), ('COMPLETED PROCESSING', 'Completed Processing'), ('ON TRANSIT', 'On Transit'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.product')),
            ],
        ),
    ]
